stages:
    - build
    - test
    - push
    - deploy

variables:
    DEPLOY_ENV: "development"

build_job:
    stage: build
    script: 
        - echo "Building Docker Image Git SHA $CI_COMMIT_SHA"
        #- docker build -t DevOps-Assignment:$CI_COMMIT_SHA

test_job:
    stage: test
    script: 
        - echo "This is the test stage script. Testing the docker image from $DOCKERHUB_USER user and pass $DOCKERHUB_PASS."

deploy_job:
    stage: deploy
    script: 
        - echo "This is the deploy stage script on $CI_COMMIT_BRANCH."
