stages:
    - build
    - test
    - deploy

variables:
    DEPLOY_ENV: "development"

build_job:
    stage: build
    script: 
        - echo "Hello $CI_COMMIT_AUTHOR. This is the build stage script."

test_job:
    stage: test
    script: 
        - echo "This is the test stage script. Testing the docker image from $DOCKERHUB_USER user."
        - mkdir -p logs/
        - echo "These are $CI_JOB_NAME job logs." > logs/test.log
        - sleep 10
    artifacts:
        paths:
            - logs/
        expire_in: 1 week

deploy_job:
    stage: deploy
    script: 
        - echo "This is the deploy stage script on $CI_COMMIT_BRANCH."
        - mkdir -p logs/
        - echo "This is $CI_JOB_NAME job logs." >> logs/app.log
    artifacts:
        paths:
            - logs/
        expire_in: 1 week
