stages:
    - build
    - test
    - push
    - deploy

variables:
    DEPLOY_ENV: "development"

build_backend:
    stage: build
    script: 
        - echo "Building Backend Docker Image - Git SHA $CI_COMMIT_SHA"
        - docker build -t DevOps-Assignment-backend:$CI_COMMIT_SHA backend/
    tags:
        - dev-runner

build_frontend:
    stage: build
    script: 
        - echo "Building Frontend Docker Image - Git SHA $CI_COMMIT_SHA"
        - docker build -t DevOps-Assignment-frontend:$CI_COMMIT_SHA frontend/
    tags:
        - dev-runner

test_job:
    stage: test
    script: 
        - echo "This is the test stage script. Testing the docker image from $DOCKERHUB_USER user and pass $DOCKERHUB_PASS."
    tags:
        - dev-runner

deploy_job:
    stage: deploy
    script: 
        - echo "This is the deploy stage script on $CI_COMMIT_BRANCH."
    tags:
        - dev-runner