stages:
    - build
    - test
    - deploy

build_job:
    stage: build
    script: 
        - echo 'Hello $GITLAB_USER_LOGIN. This is the build stage script.'

test_job:
    stage: test
    script: 
        - echo 'This is the test stage script.'
        - sleep 10

deploy_job:
    stage: deploy
    script: 
        - echo 'This is the deploy stage script on the $CI_COMMIT_BRANCH branch.'
    environment: dev
