- name: Bastion Play
  hosts: bastion-server
  become: true
  tasks:
    
    - name: Enable IP forwarding
      ansible.builtin.lineinfile:
        path: /etc/sysctl.conf
        line: net.ipv4.ip_forward=1
        state: present
      notify:
        - sysctl changed

    - name: Install netfilter-persistent
      ansible.builtin.apt:
        name: netfilter-persistent
        update_cache: true
        state: present

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        force_apt_get: true

    - name: Set NAT iptables rules
      ansible.builtin.iptables:
        table: nat
        chain: POSTROUTING
        out_interface: "{{ ansible_default_ipv4.interface }}"
        jump: MASQUERADE
        comment: "Enable NAT for private subnet"
        state: present
      notify:
        - persist iptable rules

  handlers:

    - name: sysctl changed
      ansible.builtin.command:
        cmd: sysctl -p
      listen: "sysctl changed"

    - name : persist iptable rules
      ansible.builtin.command:
        cmd: netfilter-persistent save
      listen: "persist iptable rules"
